apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: test2
    repoURL: {{ .Values.repo }}
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true