apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.test.namespace }}
    server: 'https://kubernetes.default.svc'
  source:
    path: {{ .Values.test.path }}
    repoURL: {{ .Values.repo }}
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true