apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2
  namespace: argocd
spec:
  destination:
    namespace: test2
    server: 'https://kubernetes.default.svc'
  source:
    path: test2
    repoURL: https://github.com/InfamousPotatoe/k8s.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true