apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.test.name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.test.namespace }}
    server: {{ .Values.server }}
  source:
    path: {{ .Values.test.path }}
    repoURL: {{ .Values.repo }}
    targetRevision: {{ .Values.test.branch }}
  project: default
  syncPolicy:
    automated:
      prune: {{ .Values.test.prune }}
      selfHeal: {{ .Values.test.selfHeal }}
    syncOptions:
      - CreateNamespace=true