
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.operators.name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.operators.namespace }}
    server: {{ .Values.server }}
  source:
    path: {{ .Values.operators.path }}
    repoURL: {{ .Values.repo }}
    targetRevision: {{ .Values.operators.branch }}
  project: default
  syncPolicy:
    automated:
      prune: {{ .Values.operators.prune }}
      selfHeal: {{ .Values.operators.selfHeal }}
    syncOptions:
      - CreateNamespace=true