apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: appofapps
    repoURL: https://github.com/InfamousPotatoe/k8s.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true